import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { Navbar } from "@/components/navbar";
import { Infobar } from "@/components/infobar";

export const metadata: Metadata = {
	title: "BLOG APP VASANYA",
	description: "Generated by VASANYA",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body>
				<Header />
				<main className="max-w-[1200px] m-auto grid grid-cols-[300px_1fr_300px]">
					<Navbar/>
					{children}
					<Infobar/>
				</main>
			</body>
		</html>
	);
}
